### ISSUE TITLE
There is no issue. I just wanted to say that this is phenomenal work.

### ISSUE THREAD

**Issue by bitmanic** [GV14982/async-airtable#50]
Sorry to clog up your Issues, but hopefully a little praise is welcome here. 

First of all, Airtable is awesome. It makes playing around with little data projects really easy. But...you've taken what was _easy_, and you've also made it _fun_. Thank you so much for this awesome effort. That is all. 🙃

**Comment by GV14982** [comment]
Well that is very kind of you, I really appreciate it.
If you have any feedback at all, please let me know, I'm always looking for new features to add!
