### ISSUE TITLE
Error: unable to locate global object

### ISSUE THREAD

**Issue by bitmanic** [GV14982/async-airtable#51]
**Describe the bug**
Any attempt to use async-airtable in the browser via Next.js fails due to an inability to locate the global object.

**To Reproduce**

1. Visit this CodeSandbox: https://codesandbox.io/s/silly-galileo-0zt3w?file=/pages/index.js
2. Observe in `pages/index.js` that we are referencing the browser version of `async-airtable`.
3. See error message in browser preview window.

**Expected behavior**
I expect to access the browser version of `async-airtable` within a React component.

**Screenshots**
<img width="1391" alt="Screen Shot 2020-12-30 at 5 06 31 PM" src="https://user-images.githubusercontent.com/190916/103338329-65ae5700-4ac1-11eb-8262-76856dbd1a7f.png">

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Browser: Firefox
- Version: 84

**Additional context**

Next.js offers [ways to retrieve data via SSR](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation), and the node version of `async-airtable` works perfectly within that context. However, I'd like to make some updates to Airtable from forms within React components, and that needs to happen in the browser context. I ran into this issue while attempting to make those updates.

A bit of Googling made me think that the issue might be related to `node-fetch` and/or referencing `this` instead of `globalThis`. However, this stuff isn't really my wheelhouse and I wasn't able to fork and fix on my own. Thanks in advance for your time and energy!

**Comment by bitmanic** [comment]
(This seems related to the work done in #37.)

**Comment by GV14982** [comment]
Hey there,

I tested this out, and I was able to fix the error by changing the import on line from:
`import AsyncAirtable from "asyncairtable/dist/asyncAirtable";`
to
`import AsyncAirtable from "asyncairtable";`

That seemed to fix it. Let me know if you're still having trouble!

**Comment by bitmanic** [comment]
Huh. When I perform the same action in CodeSandbox, I get `Error: API Key is required` errors (even after nuking and redefining the related env vars). When I change the import in my local dev env, I get weird CORS errors instead. Not sure how to proceed from here, aside from falling back to using Airtable's own lib for client-side JS, while still using async-airtable server-side. (That's good enough for me.)

Thanks for your time, @GV14982!

**Comment by GV14982** [comment]
I'll setup a local NextJS project and see if I can find a fix for your issue a little later today.

**Comment by GV14982** [comment]
@bitmanic I was able to get this working on [codesandbox](https://codesandbox.io/s/strange-almeida-rnfnt?file=/pages/index.js) using the env by renaming the variables with a NEXT_PUBLIC_ prefix according to the [docs](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser)

I was also able to get this working in a local NextJS project. Would you mind sharing some of your code?

**Comment by GV14982** [comment]
@bitmanic are you still having issues with this or can I close this issue?

**Comment by GV14982** [comment]
Going to close this issue for now. Let me know if you're still having issues :)

**Comment by bitmanic** [comment]
@GV14982 Sorry for the silence, and thanks for your time and energy. I'll be working on this particular project again later this week. I'll respond to this thread if need be. Thanks again!
