### ISSUE TITLE
✨ Add logic for rate limiting

### ISSUE THREAD

**Issue by GV14982** [GV14982/async-airtable#6]
When I make a request using asyncAirtable and it receives a rate limited response, retry the the request after waiting 30 seconds.

From the Airtable documentation:

> The API is limited to 5 requests per second per base. If you exceed this rate, you will receive a 429 status code and will need to wait 30 seconds before subsequent requests will succeed.

**Comment by seanmetzgar** [comment]
Looking in to how to do this without a dependency is fun. But, I found this that can be borrowed from. (specifically the memory version). https://github.com/animir/node-rate-limiter-flexible

**Comment by seanmetzgar** [comment]
and this... https://github.com/xavi-/node-simple-rate-limiter

**Comment by GV14982** [comment]
I'll take care of this.

**Comment by GV14982** [comment]
Fixed in #24
