### ISSUE TITLE
Support for views?

### ISSUE THREAD

**Issue by rossPatton** [GV14982/async-airtable#60]
**Is your feature request related to a problem? Please describe.**
I can't find any reference to Airtable Views in the docs, is querying a specific view within a table supported?

**Describe the solution you'd like**
If supported, clear documentation on how to use it. If not supported, then I would like it to be added?

**Describe alternatives you've considered**
I've tried a couple approaches using the standard airtable API, if it isn't supported I'll just end up writing my own wrapper for airtable, but i'd rather use a more standardized thing

**Comment by GV14982** [comment]
Hey @rossPatton, sorry for the delay in response.

Yes, we support views. Please see the [Select Options](https://asyncairtable.com/interfaces/selectoptions) section of the documentation. You just need to specify the name of the view in the `view` property of your select options object.
