### ISSUE TITLE
Regex FilterByFormula in Select Options not Working

### ISSUE THREAD

**Issue by anthonygualandri** [GV14982/async-airtable#67]
**Describe the bug**
When I try and use a regex formula filter per Airtable's supported formula elements I get no records back. Just wanting to confirm whether or not AsyncAirtable allows for the regex formula to be included in the filterByFormula field for select options before I try and debug my code any further. Thanks!

**To Reproduce**

const selectOptions = {
    fields: ['Name', 'Region'],
    filterByFormula: `REGEX_MATCH(ARRAYJOIN({Teachers}, ", "), "${userName}")`
 }

**Comment by GV14982** [comment]
Hi, sorry for the delay in response, let me give this a test to be sure, but all I do is URIencode that string and slap it into a query param when I make the API request to airtable, so it should work. I'll take a look and get back to you.

**Comment by GV14982** [comment]
Hey there, so I pushed this into the `next` branch. Can you install `asyncairtable@next` and let me know if you're still having this issue?
